_wandb:
    value:
        cli_version: 0.19.8
        m: []
        python_version: 3.10.9
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.9
            "5": 0.19.8
            "6": 4.47.0
            "8":
                - 5
            "12": 0.19.8
            "13": linux-x86_64
batch_size:
    value: 512
epochs:
    value: 45
img_size:
    value: 32
lr:
    value: 0.001
timesteps:
    value: 500
